name: Build macOS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-ios

        npx zx ./scripts/build.mjs
