name: Build macOS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-ios
        rustup target add aarch64-apple-ios-sim

        npx zx ./scripts/build.mjs
    - name: Upload app
      uses: actions/upload-artifact@v3
      with:
        name: StandaloneApp.app
        path: ./target/cmake-build-debug/*_artefacts/Debug/Standalone/*.app
    - name: Upload VST
      uses: actions/upload-artifact@v3
      with:
        name: Plugin.vst3
        path: ./target/cmake-build-debug/*_artefacts/Debug/VST3/*.vst3
    - name: Upload AU
      uses: actions/upload-artifact@v3
      with:
        name: Plugin.component
        path: ./target/cmake-build-debug/*_artefacts/Debug/AU/*.component
